version: '3'

services:

  postgres:
    image: postgres
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
