version: '3'

services:

  dynamodb:
    container_name: fpg-dynamodb
    image: amazon/dynamodb-local:latest
    command: [ "-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb" ]
    ports:
      - "8000:8000"
    environment:
      JAVA_OPTS: '-Xmx256m'
    networks:
      - default

  postgres:
    container_name: fpg-postgres
    image: postgres:13.3
    restart: on-failure
    ports:
      - "5433:5432"
    networks:
      - default

  redis:
    container_name: fpg-redis
    image: redis:6.2.3
    ports:
      - "6379:6379"
    networks:
      - default